### PR TITLE
feat(helm): allow upgrade checker to be disabled

### LINKED ISSUE #3436: Remove pre-upgrade check in controller
This is preventing beta-> v2.1.0 upgrades.

We should consider removing this at some point.

### PR DESCRIPTION
**Pull request by t3mi**
Potentially closes #3436

**What this PR does / why we need it**:
The purpose of the pre-upgrade checker was to block upgrades between beta -> stable releases but in the same time it blocks upgrades between stable releases. Adding such toggle allows user to opt-out from such behaviour until it would be fully removed.

**How does this PR make you feel**:
gif

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains tests
- [ ] this PR contains YAML Samples

### CODE REVIEW

**Comment by theunrepentantgeek** [comment]
Under what circumstances is the pre-upgrade-check causing upgrades to fail between stable versions?

I've just reread that code and it should not fire unless the old version in the cluster is a beta one. Is the check buggy?

I'm worried that bypassing a needed check will put the cluster into an unstable, potentially unusable, state.

**Comment by matthchr** [comment]
We just don't need the check anymore (as per #3436). I think I'd rather just rip it all out though, rather than add a Helm option to disable it conditionally.

I've sent a PR to do that here: https://github.com/Azure/azure-service-operator/pull/4217

**Comment by matthchr** [comment]
My PR removing the upgrade check entirely has merged, so I think it makes sense to close this.

Let me know if you disagree @t3mi

**Comment by t3mi** [comment]
@theunrepentantgeek we were installing the chart using terraform and for some reason it was failing at the pre-upgrade check. Unfortunately, I haven't saved the logs as we decided to use forked version of the chart w/o the check for future upgrades.

superseded by #4217

**Pull request closed without merging**
