### PR TITLE
Improve/insights samples

### PR DESCRIPTION
**Pull request by mehighlow**
Refers #2821 and #2822

**What this PR does / why we need it**:
This PR improves insights sample

**Special notes for your reviewer**:
None

### CODE REVIEW

**Comment by matthchr** [comment]
We also have tests for each sample (to ensure that the samples are correct). The tests are done using HTTP recordings and the results are checked in.

These samples have two tests associated with them: 
https://github.com/Azure/azure-service-operator/blob/main/v2/internal/controllers/recordings/Test_Samples_CreationAndDeletion/Test_Insights_v1api_CreationAndDeletion.yaml
and
https://github.com/Azure/azure-service-operator/blob/main/v2/internal/controllers/recordings/Test_Samples_CreationAndDeletion/Test_Insights_v1beta_CreationAndDeletion.yaml

In order to re-record those tests, you need to follow the instructions [here](https://azure.github.io/azure-service-operator/contributing/#running-integration-tests). Mainly you need to set up the `AZURE_SUBSCRIPTION_ID`, `AZURE_TENANT_ID`, etc.

You don't need to run every integration test, if you just run the one sample test: `Test_Samples_CreationAndDeletion`, that will re-record the those files. The actual workflow to do this is:
1. Set `AZURE_SUBSCRIPTION_ID`, etc vars
2. Delete the two existing recording files (linked above).
3. Run `TEST_FILTER=Test_Samples_CreationAndDeletion task controller:test-integration-envtest`

This should produce 2 new files (named the same as before but with different content) containing the HTTP recordings of successfully deploying that component + workspace

**Comment by mehighlow** [comment]
@matthchr, tests associated with samples have been added. PTAL.

**Review by matthchr — APPROVED** [review]

**Pull request merged**
