### PR TITLE
Fix pre-release-test task target

### PR DESCRIPTION
**Pull request by super-harsh**
**What this PR does / why we need it**:

This PR fixes the TaskFile's `controller:test-upgrade-apply-prerelease-chart` target to replace the old target `controller:gen-helm-manifest` to `controller:package-helm-manifest`

Also, fixes `create-kind-wi-storage.sh` to set --allow-blob-public-access==false for StorageAccount creation.

### CODE REVIEW

**Review by theunrepentantgeek — APPROVED** [review]

**Comment by matthchr** [comment]
> Also, fixes create-kind-wi-storage.sh to set --allow-blob-public-access==false for StorageAccount creation.

Was there an error someplace? IIRC this is the default, it shouldn't need to be specified explicitly?

**Comment by super-harsh** [comment]
@matthchr - `allow-blob-public-access` is blocked by the policy and is set to True by default.

**Comment by super-harsh** [comment]
actually, default is True for versions prior to `2023-01-01`. What version does az pick up by default? any idea?  :-?

**Comment by matthchr** [comment]
It should pick the latest API (depending on version of CLI). The docker container at least is using a new-ish version of the CLI so should have this as the default, but being explicit doesn't hurt.

**Review by matthchr — APPROVED** [review]

**Pull request merged**
