### PR TITLE
fixes samples link

### PR DESCRIPTION
**Pull request by nmeisenzahl**
**What this PR does / why we need it**:

Fixes the internal link for the samples.

**Special notes for your reviewer**:

**How does this PR make you feel**:

**If applicable**:
- [X] this PR contains documentation
- [ ] this PR contains tests

### CODE REVIEW

**Review by babbageclunk — APPROVED** [review]
Good spotting, thanks for the PR! I tweaked the path to be relative - they both seem to work but the other links in the file are relative.

**Review by davefellows — APPROVED** [review]

**Pull request merged**
