### PR TITLE
Fix breaking changes documentation ordering to be consistent

### PR DESCRIPTION
**Pull request by matthchr**
**What this PR does / why we need it**:

**Special notes for your reviewer**:

**If applicable**:
- [x] this PR contains documentation
- [ ] this PR contains tests
- [ ] this PR contains YAML Samples

### CODE REVIEW

**Review by theunrepentantgeek — COMMENTED** [review]
Won't this make them sequential, with the latest at the bottom?

I thought we wanted them in reverse order, latest at the top.

**Comment by matthchr** [comment]
> Won't this make them sequential, with the latest at the bottom?
> I thought we wanted them in reverse order, latest at the top.

It would be nice to have them backwards-ordered. Right now the issue is they're incorrectly ordered, which is worse than either forwards or backwards... let me see if I can make them ordered the way we want but in a way that's harder to mess up.

**Review by theunrepentantgeek — APPROVED** [review]

**Pull request merged**
