### PR TITLE
Fix local package aliases with "." in them

### PR DESCRIPTION
**Pull request by matthchr**
**If applicable**:
- [ ] this PR contains documentation
- [x] this PR contains tests
- [ ] this PR contains YAML Samples

### CODE REVIEW

**Review by theunrepentantgeek — CHANGES_REQUESTED** [review]
Which types have a group containing a `.` ? 

I thought we had specific logic in the loading stages of the pipeline to prevent that from happening. If there's a bug in that, we should fix it there, not patch it at the end of the process.

**Comment by matthchr** [comment]
> Which types have a group containing a . ?

`network.frontdoor` is a new group coming soon. This is added because of the [mappings we define in azure-arm](https://github.com/Azure/azure-service-operator/blob/main/v2/azure-arm.yaml#L622), combined with [this code](https://github.com/Azure/azure-service-operator/blob/main/v2/tools/generator/internal/codegen/pipeline/load_types.go#L794), produces groups containing `.` in their name.

I _think_ that this is expected and that we should tolerate it in package references? It's just until now we've not run up against it.

**Review by theunrepentantgeek — APPROVED** [review]

**Comment by theunrepentantgeek** [comment]
I think you need to add some tests, but otherwise good.

**Review by super-harsh — APPROVED** [review]

**Pull request merged**
