### PR TITLE
Feature/application security group

### PR DESCRIPTION
**Pull request by nishant221**
Closes https://github.com/Azure/azure-service-operator/issues/4291

**What this PR does / why we need it**:
Add new resource Microsoft.Network/ApplicationSecurityGroup

**Special notes for your reviewer**:

_Few additional files are generated inside `docs/hugo/content/` when I ran tasks **"doc:crd-api" & "doc:render-diagrams"**_

**How does this PR make you feel**: Excited :) 

**If applicable**:
- [X] this PR contains documentation
- [X] this PR contains tests
- [X] this PR contains YAML Samples

### CODE REVIEW

**Comment by nishant221** [comment]
@microsoft-github-policy-service agree company="Adobe"

**Comment by theunrepentantgeek** [comment]
> Few additional files are generated inside docs/hugo/content/ when I ran tasks "doc:crd-api" & "doc:render-diagrams"

You didn't need to run those tasks - we have them scheduled to run as required. No problem though. :smile:

**Review by theunrepentantgeek — APPROVED** [review]

**Comment by theunrepentantgeek** [comment]
Thanks @nishant221

**Pull request merged**
