### PR TITLE
Ensure DB connections are closed when we've finished with them

### LINKED ISSUE #1576: Bug: PostgreSqlUser opens more and more connections
**Describe the bug**
User is created and permissions are granted. PGSqlConnection idles. During time more and more connections are created and all idles. It takes some time but then the database accepts no more connection because of 100 idle connections

**To Reproduce**
Create a PostgreSqlUser CR and wait for provisioned and a little bit more.

**Expected behavior**
User is created and permissions are granted. PGSqlConnection is closed.

**Screenshots**
grafik

**Additional context**
I guess the connections are from this part:

https://github.com/Azure/azure-service-operator/blob/master/pkg/resourcemanager/psql/psqluser/psqluser_reconcile.go

There are just a view users

grafik

### PR DESCRIPTION
**Pull request by babbageclunk**
Closes #1576 

**What this PR does / why we need it**:
Before this change, the different resources would leak database connections whenever they were reconciled. Add `defer db.Close()` to all of the places that open database connections so that they are closed at the end of the method.

**Special notes for your reviewer**:
I started off making a cache to keep the `*sql.DB`s in so that they could be reused between reconciliations, but then the difficulty was ensuring we didn't keep the DBs in the cache indefinitely. One option was to hook up the database controller so it could remove the cached entry when the database was deleted, but that's quite fiddly architecturally. I also wrote [some code](https://github.com/Azure/azure-service-operator/compare/master...babbageclunk:bug/postgres-connections) to clear DBs from the cache if they haven't been requested after a fixed amount of time, which would work but would be really difficult to test (to an extent that is probably not worth it). 

**How does this PR make you feel**:
gif

### CODE REVIEW

**Review by Porges — APPROVED** [review]

**Review by theunrepentantgeek — APPROVED** [review]
Looks good. :shipit:

**Review by matthchr — APPROVED** [review]

**Comment by johgoe** [comment]
@matthchr @babbageclunk  Is there already a timeline for the next release, which includes this fix?

**Comment by matthchr** [comment]
@johgoe There's no hard deadline but I would imagine sometime in the next week. Are you waiting for this change? (I assume yes given you're asking here).

**Comment by johgoe** [comment]
@matthchr Thank you for you fast reply. Currently we have to restart our PostgreSQL Server too often. We are happy to hear that the release should be available sometime next week.

**Pull request merged**
