### PR TITLE
[WIP] Add DPP to azure yaml

### PR DESCRIPTION
**Pull request by anshulahuja98**
Closes #[issue number]

**What this PR does / why we need it**:

**Special notes for your reviewer**:

**How does this PR make you feel**:
gif

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains tests

### CODE REVIEW

**Comment by matthchr** [comment]
Hi @anshulahuja98, thanks for your contribution. Please take a look at the [adding a new codegenerated resource](https://azure.github.io/azure-service-operator/contributing/add-a-new-code-generated-resource/) documentation: I don't see the dataprotection resources in the [Azure resource manager schemas repo](https://github.com/Azure/azure-resource-manager-schemas), which is where they need to be for us to import them right now.

You can either go through that process (assuming you're on the DataProtection team) or wait until @porges PR #2084 is merged, at which point we will only rely on the Swagger (which I see dataprotection has).

**Comment by anshulahuja98** [comment]
> 

Thanks for inputs @matthchr 
Is there an ETA on the swagger PR  by @Porges ?

Our requirement of ASO is not very immediate, we can mostly wait, but would be good to know the timelines for it.

**Comment by theunrepentantgeek** [comment]
We expect PR #2084 to land in the next week or so, all going to plan.

**Comment by anshulahuja98** [comment]
> We expect PR #2084 to land in the next week or so, all going to plan.

Okay awesome!

**Comment by anshulahuja98** [comment]
@matthchr / @theunrepentantgeek is there any update on work of #2084

**Comment by matthchr** [comment]
@porges is working on it. He might have more details on ETA.

**Comment by theunrepentantgeek** [comment]
It took a whole lot more effort than we anticipated, but we've now merged #2323 which should unblock this change. I'll self assign this and will look into getting the data protection resources into ASO post the `beta.4` release.

**Comment by anshulahuja98** [comment]
That's great @theunrepentantgeek! Thank you for taking this up!

**Comment by theunrepentantgeek** [comment]
Superseded by #3078

**Pull request closed without merging**
