### PR TITLE
Add operator bundle artifacts to .gitignore

### PR DESCRIPTION
**Pull request by babbageclunk**
**What this PR does / why we need it**:
This hides the dockerfile and bundle directory that the generate-operator-bundle target (#1285) generates so they don't get accidentally added to the repository.

**How does this PR make you feel**:
gif

### CODE REVIEW

**Review by matthchr — APPROVED** [review]

**Review by theunrepentantgeek — APPROVED** [review]
Love the choice of gif. 😁

**Comment by babbageclunk** [comment]
Hopefully(?) the test failure was because of an ARM outage.

**Pull request merged**
