### PR TITLE
Typo "Postgre SQL"→"PostgreSQL"

### PR DESCRIPTION
**Pull request by hyoshioka0128**
https://github.com/Azure/azure-service-operator/blob/main/docs/v1/services/postgresql/postgresql.md
#PingMSFTDocs

Closes #[issue number]

**What this PR does / why we need it**:

**Special notes for your reviewer**:

**How does this PR make you feel**:
gif

**If applicable**:
- [x] this PR contains documentation
- [ ] this PR contains tests

### CODE REVIEW

**Review by theunrepentantgeek — APPROVED** [review]

**Comment by theunrepentantgeek** [comment]
Thanks @hyoshioka0128, much appreciated.

**Comment by matthchr** [comment]
//azp run

**Pull request merged**
