### PR TITLE
Fix Workload ID docs

### PR DESCRIPTION
**Pull request by nojnhuh**
**What this PR does / why we need it**: This change fixes a couple of minor issues I ran into in the docs while trying to set up ASO to use Workload Identity.

**Special notes for your reviewer**: After these tweaks, I did get it up and running!

**How does this PR make you feel**:
gif

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains tests

### CODE REVIEW

**Review by matthchr — APPROVED** [review]

**Comment by theunrepentantgeek** [comment]
Thanks @nojnhuh

**Pull request merged**
