### PR TITLE
Elide subnet IPConfiguration field when it passes 2000 entries

### LINKED ISSUE #4428: Bug: Reconciling VirtualNetworksSubnet fails with "Request entity too large: limit is 3145728"
## Describe the bug

The bug manifests on our cluster created with the following networking parameters:
```shell
az aks show --subscription ExampleSubscription -n example-cluster-name -g example-cluster-name-rg -o table --query networkProfile

NetworkPlugin    NetworkPolicy    NetworkDataplane    ServiceCidr    DnsServiceIp    OutboundType    LoadBalancerSku    PodLinkLocalAccess
---------------  ---------------  ------------------  -------------  --------------  --------------  -----------------  --------------------
azure            azure            azure               10.100.0.0/16  10.100.0.10     loadBalancer    standard           IMDS
```

And it has 20 Agent Pools, with the following sizes:
```shell
 az aks show --subscription ExampleSubscription -n example-cluster-name -g example-cluster-name-rg -o table --query "agentPoolProfiles[].{Count: count, maxCount: maxCount, maxPods: maxPods}"
Count    MaxCount    MaxPods
-------  ----------  ---------
0        3           20
5        7           150
0        3           80
2        5           110
0        50          100
36       60          100
27       100         100
12       20          100
11       33          110
1        4           110
3        8           80
0        0           100
5        10          100
2        7           100
4        30          100
5        30          100
0        3           20
15       30          100
3        3           20
2        7           80
```

CAPZ created a `VirtualNetworksSubnet` ASO CR for that cluster with the following configuration:
```
az network vnet subnet show --ids "example/subnet/id" -o table --query "{addressPrefix: addressPrefix, privateEndpointNetworkPolicies: privateEndpointNetworkPolicies, privateLinkServiceNetworkPolicies: privateLinkServiceNetworkPolicies}"

AddressPrefix    PrivateEndpointNetworkPolicies    PrivateLinkServiceNetworkPolicies
---------------  --------------------------------  -----------------------------------
10.0.0.0/16      Disabled                          Enabled
```

When the AgentPools reach somewhere close to the "counts" above, the `VirtualNetworksSubnet` object in azure grows in size to around 5.6mb, if fills up with thousands of entries in the `ipConfigurations` field:
```shell
az network vnet subnet show --ids /subscriptions/.../subnets/example-cluster-subnet > example-cluster-subnet.json
ls -lh example-cluster-subnet.json
-rw-r--r--@ 1 danilo.uipath  staff   5.6M Nov  4 12:37 example-cluster-subnet.json
cat example-cluster-subnet.json| jq '.ipConfigurations | length'
14006
cat example-cluster-subnet.json| jq '.ipConfigurations[0].id | length'
305
cat example-cluster-subnet.json| jq '.ipConfigurations[0].resourceGroup | length'
60
```

ASO then tries to persist the `ipConfigurations` into the `VirtualNetworksSubnet` CR's status and this causes the api server to return:
```
E1107 10:21:00.621890       1 generic_reconciler.go:143] "msg"="Failed to commit object to etcd" "error"="updating example-ns/example-cluster-name-vnet-example-cluster-name-subnet resource: Request entity too large: limit is 3145728" "logger"="controllers.VirtualNetworksSubnetController" "name"="example-cluster-name-example-cluster-name-subnet" "namespace"="example-ns"
```

Azure Service Operator Version: v2.8.0

## Expected behavior

The `VirtualNetworksSubnet` to continue reconciling successfuly for any scalable size of my Agent Pools.

## To Reproduce

Create a `VirtualNetworksSubnet` CR for an Azure Cloud Subnet with a large number of `ipConfigurations` and wait for the controller to attempt to sync it.

## Additional context

This issue relates to another issue in the CAPZ project https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/4649

### PR DESCRIPTION
**Pull request by matthchr**
Fixes #4428.

- [ ] this PR contains documentation
- [ ] this PR contains tests
- [ ] this PR contains YAML Samples

### CODE REVIEW

**Comment by matthchr** [comment]
No tests because it's hard to test with our infra right now. I'm working on #3679 on the side... but in the meantime tested this manually and confirmed it worked.

**Review by theunrepentantgeek — APPROVED** [review]

**Comment by theunrepentantgeek** [comment]
We should put something into our docs about why we remove the connection, and why we remove it all, so that we don't get a bug report later on.

**Comment by matthchr** [comment]
Planning to merge this and will follow up with a separate PR that fixes the documentation problem by adding the ability to override descriptions in the codegenerator pipeline.

**Pull request merged**
