### PR TITLE
increase test coverage  for set.go

### LINKED ISSUE #2945: increase test coverage for `set.go`
**Describe the current behavior**
The current unit test coverage is 45% [https://app.codecov.io/gh/Azure/azure-service-operator/tree/master/v2/internal/set](https://app.codecov.io/gh/Azure/azure-service-operator/tree/master/v2/internal/set)

**Describe the improvement**
I would like to increase the test coverage

**Additional context**
NA

### PR DESCRIPTION
**Pull request by khareyash05**
Closes #2945 

**What this PR does / why we need it**:

**Special notes for your reviewer**:

**How does this PR make you feel**:
gif

**If applicable**:
- [ ] this PR contains documentation
- [X] this PR contains tests

### CODE REVIEW

**Review by theunrepentantgeek — CHANGES_REQUESTED** [review]
Thanks for the PR, improving the coverage is helpful.

We avoid having monolithic test methods in this project because they conceal information when they fail; usually only the first failure is reliable. 

Please split `TestSet` into a series of individual tests, each of which tests one scenario. We often use [Roy Osherove's test naming conventions](https://osherove.com/blog/2012/5/15/test-naming-conventions-with-unit-of-work.html) where each test name is made up of three parts: `UnitOfWork_Scenario_Expectation`. For some examples of this, see [flagged_type_test.go](https://github.com/Azure/azure-service-operator/blob/main/v2/tools/generator/internal/astmodel/flagged_type_test.go) or [identifier_factory_test.go](https://github.com/Azure/azure-service-operator/blob/main/v2/tools/generator/internal/astmodel/identifier_factory_test.go)

Also, consider importing the `gomega` library to write the asserts - they take care of generating good errors when the test fails.

To illustrate, your first test might become something like this:

``` go
func TestSet_WhenConstructedWithItems_HasExpectedSize(t *testing.T) {
        t.Parallel()
        g := NewGomegaWithT(t)

	set := Make(1, 2, 3)
        g.Expect(set).To(HaveLength(3))
}
```

Thanks for the contribution!

**Comment by khareyash05** [comment]
Could you please review @theunrepentantgeek .

**Review by theunrepentantgeek — APPROVED** [review]

**Comment by theunrepentantgeek** [comment]
Thanks for updating those tests, they look good. I've triggered our CI to run, and will merge once that passes.

**Review by super-harsh — APPROVED** [review]

**Comment by khareyash05** [comment]
Is my PR ready to merge? @super-harsh @theunrepentantgeek ?

**Comment by khareyash05** [comment]
Thank you @matthchr @theunrepentantgeek @super-harsh for merging the PR. I would like to contribute more to this project.Is there any communication channel through which I can communicate with the team ?

**Pull request merged**
